### ISSUE TITLE
The Italian "Redeem Tirolo" mission will not fire, even though I own the entire area of Tirolo

### ISSUE THREAD

**Issue by phlnx** [AlejandroGiner/Lux-in-Tenebris#14]
Playing as Italy on 1.30. I followed the instructions and created a local mod from the source material here, I think last week.

Thank you for your attention.

**Comment by AlejandroGiner** [comment]
Thank you for reporting this bug. I have fixed it in the master branch. Redownloading the mod should work (for ongoing saves too as far as I know.)

**Comment by phlnx** [comment]
Thank you very much for your prompt reply! I will re-create the local mod then.

**Comment by phlnx** [comment]
Hello, I can confirm that now I could complete the mission.

However, the next mission in line "Humiliate Austria" can also be executed, although I don't think its requirements are met. Austria IS in the game and it is not my vassal (I still play as Italy).

![immagine](https://user-images.githubusercontent.com/7044713/94989112-99d1b480-0572-11eb-8068-fd5aeda0d3b4.png)

![immagine](https://user-images.githubusercontent.com/7044713/94989133-b968dd00-0572-11eb-962d-ee8ad4f3d861.png)

Is it something wrong I did?

Thank you for your help and have a nice day.

**Comment by AlejandroGiner** [comment]
Do you fulfill the third condition? Is Austria neither a Great Power or Emperor of HRE?

**Comment by phlnx** [comment]
Yes I did. Austria is not a great power and the Empire went protestant so Austria can't play.
Ohhh now I see my mistake. I was convinced the third option was optional. My mistake. I will close the issue. Thank you.
